load("//third_party/bazel_rules/rules_cc/cc:cc_binary.bzl", "cc_binary")

package(default_visibility = [
    ":default_visibility",
])

package_group(
    name = "default_visibility",
    packages = [
        "//local_agents/...",
    ],
)
